### PR TITLE
Incorporate a community extension directory

### PR DESCRIPTION
**Pull request by BCPianist**
Hi there, I thought it could be much useful for users to have a dedicated directory for usermade extensions. Not only would coders be inspired, those who do not know how to code could benefit from the other's experience. 
Anyway, I hope you like it...

Note: A README.md explaining this and listing (with their respective links) the usermade extensions could be useful given that you take this idea.

### CODE REVIEW

**Comment by dehesa** [comment]
I agree with this. I am trying to build a function and having more examples would be terrible helpful.

**Comment by nikolaeu** [comment]
Awesome idea @BCPianist 👍

**Comment by gomako** [comment]
Is there a place to put community made extensions? Sorry if I have missed something, I am relatively new to open source stuff!

**Comment by nikolaeu** [comment]
@gomako merged!

**Pull request merged**
